// ********RoostGPT********
// Test generated by RoostGPT for test NodeTesting using AI Type Open AI and AI Model gpt-4



// ********RoostGPT********
const { generateLovePercent } = require('../features');

describe('Test the generateLovePercent function', () => {

  test('It should return a string', () => {
    expect(typeof generateLovePercent()).toBe('string');
  });

  test('It should return a string ending with %', () => {
    expect(generateLovePercent().endsWith('%')).toBe(true);
  });

  test('It should return a string in which the number before % is between 0 and 100', () => {
    const result = generateLovePercent();
    const number = parseInt(result.substring(0, result.length - 1));
    expect(number).toBeGreaterThanOrEqual(0);
    expect(number).toBeLessThanOrEqual(100);
  });

});
